
version: '3.9'

services:
  tj-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      JWT_SECRET_KEY: supersecretkey
